version: '2.1'
services:
  zookeeper:
    image: debezium/zookeeper:0.9.5.Final
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  kafka:
    image: debezium/kafka:0.9.5.Final
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
  mysql:
    build: ./mysql-image/
    image: andreformento/debezium-mysql:0.9.5.Final
    ports:
     - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=debezium
     - MYSQL_USER=mysqluser
     - MYSQL_PASSWORD=mysqlpw
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  connect-base:
    build: ./connect-base/
    image: andreformento/connect-base:0.9.5.Final
    #image: debezium/connect-base:0.9.5.Final
  connect:
    build: ./connect/
    image: andreformento/connect:0.9.5.Final
    #image: debezium/connect:0.9.5.Final
    ports:
     - 8083:8083
    links:
     - kafka
     - mysql
    depends_on:
      mysql:
        condition: service_healthy
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses
    volumes:
     - ${PWD}/connect-config:/connect-config/
